### ISSUE TITLE
Budullangr Galaxy

### ISSUE THREAD

**Issue by AeonStarfighter** [spip01/nms-bhs-db#16]
Hello - 

I'm playing "No Man's Sky" on PlayStation4, and want to search for cool starships and discoveries in the "Budullangr" galaxy.  However, the option to search this galaxy does not exist in the drop-down menu.  Yet, I can apparently upload discoveries for Budullangr.  Does this mean there are zero current entries for Budullangr?  Or is this simply a bug?

Thank you!

**Comment by CEbbinghaus** [comment]
This is fixed in the current live version of the app. If however, you are still experiencing problems then feel free to report them to the new Repository: [blackholesuns/nmsce](https://github.com/blackholesuns/nmsce)
