### ISSUE TITLE
elkupalos galaxy

### ISSUE THREAD

**Issue by Tijscher** [spip01/nms-bhs-db#18]
HI. On the searchpage the elkupalos galaxy is not selectable in the dropdown menu. Maybe you can fix this.
Thanks in advance. Great page.
Greetz
Tijscher

**Comment by CEbbinghaus** [comment]
I believe this is working in the most recent version, however if you still experience issues feel free to lodge a new ticket under the new Repository location: [blackholesuns/nmsce](https://github.com/blackholesuns/nmsce)
