### ISSUE TITLE
naves

### ISSUE THREAD

**Issue by nerdnoTTus** [spip01/nms-bhs-db#23]
eu nao consigo achar absolutamente nenhuma nada no site, nao aparece nada com minhas pesquisas

**Comment by CEbbinghaus** [comment]
Sorry, this Repository is maintained by English speakers and therefore we kindly ask you to lodge your issues in English too. Feel free to lodge a new issue in English under the new Repository location: [blackholesuns/nmsce](https://github.com/blackholesuns/nmsce)
