### ISSUE TITLE
Site issue (nmsce.com)

### ISSUE THREAD

**Issue by Devilin-Pixy** [spip01/nms-bhs-db#30]
It appears there is a website issue as of today. When moving my mouse over ship parts, they automatically turn yellow/orange, sometimes sticking, sometimes changing back, but without having even clicked. Search results also appear to show different from normal. These issues were asked about/reported on the NMS Discord and figured I'd report them here. The issue appears on both Mobile as Desktop versions. Just some weird unusual behaviour, which can likely quickly be resolved. 

Note: I am seeing the Chrome Dev Console report issues with the DOM; finding elements with non-unique id's, which might be related to the issue at hand

**Comment by SteampunkZapper** [comment]
I second this. Further info:
This seems to have started when Reddit went down. (windows 10 and android)
Mouseover ship parts turns them gold but they are rarely blue/clickable, and when they are, mouseover turns them gold again. Clicking search doesn't always work, but when it does, you get results as a tiny icon with the part selector to the right.

**Comment by shadrays** [comment]
Would be nice if the app creator would fix this issue, app is useless as is.

**Comment by Devilin-Pixy** [comment]
The site currently appears to be working fine again.

If someone can confirm the issue having been fixed, this can be closed. Else I will close it, if it remains fixed for some time.

**Comment by shadrays** [comment]
I can confirm the site is working again as of this posting, much thanks to who ever got it fixed.
